
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 05 18:07:57 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 20;
  public static final int SQUOT = 41;
  public static final int ABST = 11;
  public static final int CONST = 9;
  public static final int CHAR = 25;
  public static final int LPAREN = 44;
  public static final int SEMI = 37;
  public static final int INT = 23;
  public static final int FOR = 19;
  public static final int MINUS = 28;
  public static final int RPAREN = 45;
  public static final int STATIC = 10;
  public static final int GRTHAN = 43;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 39;
  public static final int ORD = 4;
  public static final int CLASS = 12;
  public static final int DIV = 31;
  public static final int PLUS = 27;
  public static final int IF = 16;
  public static final int THIS = 14;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 24;
  public static final int RETURN = 7;
  public static final int EQUAL = 29;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int NUMBER = 51;
  public static final int MOD = 35;
  public static final int IDENT = 52;
  public static final int BREAK = 21;
  public static final int VOID = 22;
  public static final int LSTHAN = 42;
  public static final int LBRACK = 48;
  public static final int SWITCH = 18;
  public static final int COLON = 38;
  public static final int LBRACE = 46;
  public static final int ELSE = 17;
  public static final int RBRACK = 49;
  public static final int ENUM = 26;
  public static final int QUEST = 36;
  public static final int RBRACE = 47;
  public static final int PROG = 2;
  public static final int EXTEND = 13;
  public static final int STRING = 50;
  public static final int LEN = 6;
  public static final int CHR = 5;
  public static final int PRINT = 3;
  public static final int LENGTH = 8;
}

