package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;

parser code 
{:
	boolean errorDetected = false;   
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSyntax error!", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatal error, parsing cannot be continued!", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" on line: ").append(((Symbol)info).left);
        System.err.println(msg.toString());
    }
    
    public void report_info(String message, Object info) {
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" on line: ").append(((Symbol)info).left);
        System.err.println(msg.toString());
    }
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		System.err.println(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROG, PRINT, RETURN, LENGTH, READ, CASE;
terminal CONST;
terminal TRUE, FALSE;
terminal ABST, CLASS, EXTEND, NEW;
terminal IF, ELSE, SWITCH, FOR, CONT, BREAK;
terminal VOID, ENUM;
terminal DECREMENT, INCREMENT, PLUS, MINUS, EQUAL, MUL, DIV, AND, OR, MOD;
terminal DEQUAL, NEQUAL, GREQTHAN, LSEQTHAN;
terminal QUEST, SEMI, COLON, COMMA, DOT, LSTHAN, GRTHAN;
terminal LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK;
terminal String CHAR;
terminal Integer NUMBER;
terminal String IDENT;

nonterminal Program, AnyDecl0N, AnyDecl;
nonterminal VarDecl, VarDeclMult1N, VarDeclSingle, VarDecl0N;
nonterminal ConstDecl, ConstDeclMult1N, ConstDeclSingle;
nonterminal ClassDecl, ClassDeclBody;
nonterminal MethodDecl, MethodDeclClassBody, MethodDecl0N;
nonterminal EnumDecl, EnumDeclItem1N, EnumDeclItem;
nonterminal AbstractClassDecl, AbstractClassDeclBody, AbstractClassDeclBodyDecl, AbstractMethodDecl;
nonterminal Type;
nonterminal FormPars, FormPars01;
nonterminal Statement0N, Statement;
nonterminal SwitchStatement, SwitchCaseStatement01, SwitchCaseStatement;
nonterminal DesignatorStatement, DesignatorStatement01;
nonterminal ActPars01, ActPars;
nonterminal Condition, Condition01, CondTerm, CondFact;
nonterminal Expr, ExprAddition, Term, Factor, Designator;
nonterminal TernaryExpr, OrExpr, AndExpr, RelExpr, AddExpr;
nonterminal Assignop, Relop, Addop, Mulop;
nonterminal AllTypesConst, NumConst, CharConst, BoolConst;
nonterminal ExprNormal, Minus01, TermAddition0N;

precedence left ELSE;

/* ostalo mi abstract */

Program ::= (Program) PROG IDENT AnyDecl0N LBRACE MethodDecl0N RBRACE;

AnyDecl0N ::= (AnyDeclList) AnyDecl0N AnyDecl | (AnyDeclEmpty) /* epsilon */;

AnyDecl ::= (AnyDeclConst) ConstDecl 
		| (AnyDeclVar) VarDecl 
		| (AnyDeclClass) ClassDecl 
		| (AnyDeclEnum) EnumDecl 
		| (AnyDeclAbstractClass) AbstractClassDecl;

MethodDecl0N ::= (MethodDeclList) MethodDecl0N MethodDecl | (MethodDeclEmpty) /* epsilon */;

ConstDecl ::= (ConstDecl) CONST Type ConstDeclMult1N SEMI;

ConstDeclMult1N ::= (ConstDeclMultSingle) ConstDeclSingle | (ConstDeclMultList) ConstDeclMult1N COMMA ConstDeclSingle;

ConstDeclSingle ::= (ConstDeclSingle) IDENT EQUAL AllTypesConst;

AllTypesConst ::= (AllTypesConstNum) NumConst | (AllTypesConstChar) CharConst | (AllTypesConstBool) BoolConst;

NumConst ::= (NumConst) NUMBER;
CharConst ::= (CharConst) CHAR:charValue;
BoolConst ::= (BoolConstTrue) TRUE | (BoolConstFalse) FALSE;

VarDecl ::= (VarDecl) Type VarDeclMult1N SEMI;

VarDeclMult1N ::= (VarDeclMultSingle) VarDeclSingle | (VarDeclMultList) VarDeclMult1N COMMA VarDeclSingle;

VarDeclSingle ::= (VarDeclSingleScalar) IDENT | (VarDeclSingleArray) IDENT LBRACK RBRACK;

EnumDecl ::= (EnumDecl) ENUM IDENT LBRACE EnumDeclItem1N RBRACE;

EnumDeclItem1N ::= (EnumDeclItemSingle) EnumDeclItem | (EnumDeclItemList) EnumDeclItem1N COMMA EnumDeclItem;

EnumDeclItem ::= (EnumDeclItemName) IDENT | (EnumDeclItemValue) IDENT EQUAL NumConst;

ClassDecl ::= (ClassDeclNoExtend) CLASS IDENT LBRACE ClassDeclBody RBRACE 
			| (ClassDeclExtend) CLASS IDENT EXTEND Type LBRACE ClassDeclBody RBRACE; 

ClassDeclBody ::= (ClassDeclBody) VarDecl0N MethodDeclClassBody;

VarDecl0N ::= (VarDeclList) VarDecl0N VarDecl | (VarDeclNone) /* epsilon */;

MethodDeclClassBody ::= (MethodDeclClassBodyExist) LBRACE MethodDecl0N RBRACE | (MethodDeclClassBodyEmpty) /* epsilon */;

AbstractClassDecl ::= (AbstractClassDeclRegular) ABST CLASS IDENT LBRACE AbstractClassDeclBody RBRACE 
				    | (AbstractClassDeclExtend) ABST CLASS IDENT EXTEND Type LBRACE AbstractClassDeclBody RBRACE;

AbstractClassDeclBody ::= (AbstractClassDeclBodyVarDecl) VarDecl0N 
						| (AbstractClassDeclBodyVarDeclBodyDecl) VarDecl0N LBRACE AbstractClassDeclBodyDecl RBRACE;

AbstractClassDeclBodyDecl ::= (AbstractClassDeclBodyDeclAbsAdded) AbstractClassDeclBodyDecl AbstractMethodDecl SEMI 
							| (AbstractClassDeclBodyDeclMethodAdded) AbstractClassDeclBodyDecl MethodDecl | (AbstractClassDeclBodyDeclEmpty)/* epsilon */;

AbstractMethodDecl ::= (AbstractMethodDeclTyped) ABST Type IDENT LPAREN FormPars01 RPAREN 
					 | (AbstractMethodDeclVoid) ABST VOID IDENT LPAREN FormPars01 RPAREN ;

MethodDecl ::= (MethodDeclTyped) Type IDENT LPAREN FormPars01 RPAREN VarDecl0N LBRACE Statement0N RBRACE
			|  (MethodDeclVoid) VOID IDENT LPAREN FormPars01 RPAREN VarDecl0N LBRACE Statement0N RBRACE;

FormPars ::= (FormParsSingle) Type VarDeclSingle | (FormParsMultiple) FormPars COMMA Type VarDeclSingle; 

FormPars01 ::= (FormParsExist) FormPars | (FormParsEmpty) /* epsilon */ ;

Type ::= IDENT;

Statement ::= (StatementDesignatorStatement) DesignatorStatement SEMI
			| (StatementIf) IF LPAREN Condition RPAREN Statement 
			| (StatementIfElse) IF LPAREN Condition RPAREN Statement ELSE Statement
			| (StatementBreak) BREAK SEMI
			| (StatementContinue) CONT SEMI
			| (StatementReturnNone) RETURN SEMI 
			| (StatementReturnValue) RETURN Expr SEMI
			| (StatementRead) READ LPAREN Designator RPAREN SEMI
			| (StatementPrint1Arg) PRINT LPAREN Expr RPAREN SEMI 
			| (StatementPrint2Arg) PRINT LPAREN Expr COMMA NumConst RPAREN SEMI 
			| (StatementSwitch) SwitchStatement
			| (StatementFor) FOR LPAREN DesignatorStatement01 SEMI Condition01 SEMI DesignatorStatement01 RPAREN Statement
			| (StatementStatementBlock) LBRACE Statement0N RBRACE; 

Statement0N ::= (StatementList) Statement0N Statement | (StatementEmpty) /* epsilon */ ;

SwitchStatement ::= SWITCH LPAREN Expr RPAREN LBRACE SwitchCaseStatement01 RBRACE;

SwitchCaseStatement01 ::= (SwitchCaseStatementN) SwitchCaseStatement01 SwitchCaseStatement | (SwitchCaseStatement0)/* epsilon */ ;

SwitchCaseStatement ::= CASE NumConst COLON Statement0N;

DesignatorStatement01 ::= (DesignatorStatementExist) DesignatorStatement | (DesignatorStatementEmpty) /* epsilon */;

Condition01 ::= (ConditionExist) Condition | (ConditionEmpty) /* epsilon */ ;

DesignatorStatement ::= (DesignatorStatementAssign) Designator Assignop Expr
					|   (DesignatorStatementFuncCall) Designator LPAREN ActPars01 RPAREN 
					|   (DesignatorStatementIncrement) Designator INCREMENT
					| 	(DesignatorStatementDecrement) Designator DECREMENT;

ActPars ::= (ActPars1) Expr 
		  | (ActParsN)ActPars COMMA Expr;

ActPars01 ::= (ActParsExist) ActPars | (ActParsEmpty) /* epsilon */;

Condition ::= (Condition1) CondTerm 
			| (ConditionN) Condition OR CondTerm;

CondTerm ::= (CondTerm1) CondFact 
		   | (CondTermN) CondTerm AND CondFact;

CondFact ::= (CondFact1) ExprNormal 
   		   | (CondFactN) CondFact Relop ExprNormal;

Expr ::= (ExprExprNormal) ExprNormal 
	   | (ExprTernaryExpr) TernaryExpr;

ExprNormal ::= Minus01 TermAddition0N;

Minus01 ::= (MinusExist) MINUS | (MinusEmpty) /* epsilon */ ;

TermAddition0N ::= (TermAddition1)Term 
				 | (TermAdditionN) TermAddition0N Addop Term;

TernaryExpr ::= Condition QUEST Expr COLON Expr;

Term ::= (TermFactor) Factor 
	   | (TermMulopFactor) Term Mulop Factor;

Factor ::= (FactorDesignator) Designator 
         | (FactorDesignatorFuncCall) Designator LPAREN ActPars01 RPAREN
		 | (FactorNumConst) NumConst 
		 | (FactorCharConst) CharConst 
		 | (FactorBoolConst) BoolConst 
		 | (FactorNewType) NEW Type 
		 | (FactorNewTypeIndexed) NEW Type LBRACK Expr RBRACK
		 | (FactorParen) LPAREN Expr RPAREN;

Designator ::= (DesignatorIdent) IDENT 
			 | (DesignatorDotIdent) Designator DOT IDENT 
			 | (DesignatorDotLenght) Designator DOT LENGTH 
			 | (DesignatorIndexed) Designator LBRACK Expr RBRACK;

Assignop ::= EQUAL;

Relop ::= DEQUAL | NEQUAL | GRTHAN | GREQTHAN | LSTHAN | LSEQTHAN;

Addop ::= (AddopPLUS) PLUS | (AddopMINUS) MINUS;

Mulop ::= (MulopMUL) MUL | (MulopDIV) DIV | (MulopMOD) MOD;
