package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;

parser code {:
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		System.err.println(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROG, PRINT, ORD, CHR, LEN, RETURN, LENGTH;
terminal CONST, STATIC;
terminal TRUE, FALSE;
terminal ABST, CLASS, EXTEND, THIS, NEW;
terminal IF, ELSE, SWITCH, FOR, CONT, BREAK;
terminal VOID, ENUM;
terminal DECREMENT, INCREMENT, PLUS, MINUS, EQUAL, MUL, DIV, AND, OR, NOT, MOD;
terminal QUEST, SEMI, COLON, COMMA, DOT, LSTHAN, GRTHAN;
terminal LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK;
terminal String CHAR;
terminal Integer NUMBER;
terminal String IDENT;

nonterminal Program;
nonterminal VarDecl, VarDeclMult, VarDeclSingle, VarDeclRepeated;
nonterminal ConstDecl, ConstDeclMult, ConstDeclSingle;
nonterminal ClassDecl, ClassDeclBody;
nonterminal MethodDecl, MethodDeclRepeated, MethodDeclClassBody;
nonterminal Type;
nonterminal AllTypesConst, NumConst, CharConst, BoolConst;

/* ostalo mi abstract */

Program ::= PROG IDENT ProgramParts LBRACE MethodDeclMultiple RBRACE;

ProgramParts ::= ProgramParts AnyDecl | /* epsilon */;

AnyDecl ::= ConstDecl | VarDecl | ClassDecl | EnumDecl | AbstractClassDecl;

MethodDeclMultiple ::= MethodDeclMultiple MethodDecl | /* epsilon */;

EnumDecl ::= ENUM IDENT LBRACE EnumDeclItems RBRACE;

EnumDeclItems ::= EnumDeclItem | EnumDeclItems COMMA EnumDeclItem;

EnumDeclItem ::= IDENT | IDENT EQUAL NumConst;

ClassDecl ::= CLASS IDENT LBRACE ClassDeclBody RBRACE | CLASS IDENT EXTEND Type LBRACE ClassDeclBody RBRACE; 

ClassDeclBody ::= VarDeclRepeated MethodDeclClassBody;

VarDeclRepeated ::= VarDeclRepeated VarDecl | /* epsilon */;

MethodDeclClassBody ::= LBRACE MethodDeclRepeated RBRACE | /* epsilon */;

MethodDeclRepeated ::= MethodDeclRepeated MethodDecl | /* epsilon */;

MethodDecl ::= Type IDENT LPAREN FormPars RPAREN VarDeclRepeated LBRACE Statements RBRACE
			|  VOID IDENT LPAREN FormPars RPAREN VarDeclRepeated LBRACE Statements RBRACE;

FormPars ::= Type VarDeclSingle | FormPars COMMA Type VarDeclSingle; 

Statements ::= Statements Statement | /* epsilon */ ;

Statement ::= DesignatorStatement SEMI
			| IF LPAREN Condition RPAREN Statement | IF LPAREN Condition RPAREN Statement ELSE STATEMENT
			| BREAK SEMI
			| CONT SEMI
			| RETURN SEMI | RETURN Expr SEMI
			| READ LPAREN Designator RPAREN SEMI
			| SWITCH LPAREN Expr RPAREN SEMI | SWITCH LPAREN Expr COMMA NumConst RPAREN SEMI
			| FOR LPAREN DesignatorStatement01 SEMI Condition01 SEMI DesignatorStatement01 RPAREN Statement
			| LBRACE Statements RBRACE; 

DesignatorStatement ::= Designator Assignop Expr
					|   Designator LPAREN ActPars01 RPAREN 
					|   Designator INCREMENT
					| 	Designator DECREMENT;

DesignatorStatement01 ::= DesignatorStatement | /* epsilon */;

ActPars01 ::= ActPars | /* epsilon */;

ActPars ::= Expr | ActPars COMMA Expr;

Condition ::= CondTerm | Condition OR CondTerm;

CondTerm ::= CondFact | CondTerm AND CondFact;

CondFact ::= Expr | Expr Relop Expr;

Expr ::= ExprAddition
	   | Condition QUEST Expr COLON Expr;

ExprAddition ::= MINUS Term | ExprAddition Addop Term;

Term ::= Factor | Term Mulop Factor;

Factor ::= Designator | Designator LPAREN ActPars01 RPAREN
		|  NumConst | CharConst | BoolConst 
		|  NEW Type | NEW Type LBRACK Expr RBRACK
		|  LPAREN Expr RPAREN;

Designator ::= IDENT | Designator DOT IDENT | Designator DOT LENGTH | Designator LBRACK Expr RBRACK;

Assignop ::= EQUAL;

Relop ::= DEQUAL | NEQUAL | GRTHAN | GREQTHAN | LSTHAN | LSEQTHAN;

Addop ::= PLUS | MINUS;

Mulop ::= MUL | DIV | MOD;

ConstDecl ::= CONST Type ConstDeclMult SEMI;

ConstDeclMult ::= ConstDeclSingle | ConstDeclMult COMMA ConstDeclSingle;

ConstDeclSingle ::= IDENT EQUAL AllTypesConst;

VarDecl ::= Type VarDeclMult SEMI;

VarDeclMult ::= VarDeclSingle | VarDeclMult COMMA VarDeclSingle;

VarDeclSingle ::= IDENT | IDENT LBRACK RBRACK;

Type ::= IDENT;

AllTypesConst ::= NumConst | CharConst | BoolConst;

NumConst ::= NUMBER;
CharConst ::= CHAR;
BoolConst ::= TRUE | FALSE;
